# Render deployment configuration
services:
  - type: web
    name: nexus-bids-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: nexus-bids-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://e-bidding-1.onrender.com
      - key: CLOUDINARY_CLOUD_NAME
        value: your-cloudinary-cloud-name
      - key: CLOUDINARY_API_KEY
        value: your-cloudinary-api-key
      - key: CLOUDINARY_API_SECRET
        value: your-cloudinary-api-secret

databases:
  - name: nexus-bids-db
    plan: free
